### PR TITLE
Update get cover art from itunes cause CORS problem.

### PR DESCRIPTION
**Pull request by PeWe79**
New methods get cover art from itunes because CORS problem when on mobile device (iOS).

### CODE REVIEW

**Comment by gAlleb** [comment]
Thanks @PeWe79! And for cleaning the code)

Yeah, an old problem. But I've noticed that changing User-Agent works that's why it looks strange)
```
          headers: {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15'
          }
```

However, the 'returns' contain `artist, title...` and no `collectionViewUrl` in case of failure

```
        if (response.status === 403) {
        const results = {
          title: title,
          artist: artist,
          artworkUrl: coverArt,
        }
        return results
      }

      const data = response.ok ? await response.json() : {}
      if (!data.results || data.results.length === 0) {
        const results = {
          title: title,
          artist: artist,
          artworkUrl: coverArt,
        }
        return results
      }
```

Am I getting something wrong?

**Comment by PeWe79** [comment]
Hi @gAlleb thats can be return `collectionViewUrl` also. But just an temporary, cause no request from metadata coming. But response from iTunes can be return many data.

**Comment by PeWe79** [comment]
However, if return `collectionViewUrl` is failure, maybe can be use `#` :blush:

**Comment by gAlleb** [comment]
Thanks! Made some minor changes.

**Pull request merged**
